steps:
  - name: 'gcr.io/cloud-builders/docker'
    env:
      - DOCKER_BUILDKIT=1
      - DOCKER_REGISTRY=quay.io
      - DOCKER_REPOSITORY=gravitational/docs
      - DOCKER_TAG=latest
    secretEnv:
      - QUAYIO_DOCKER_USERNAME
      - QUAYIO_DOCKER_PASSWORD
    script: .cloudbuild/publish-image.sh 
availableSecrets:
  secretManager:
  - versionName: projects/771512790633/secrets/ci_docs-quay_io_username/versions/1
    env: QUAYIO_DOCKER_USERNAME
  - versionName: projects/771512790633/secrets/ci_docs_quay_io_password/versions/1
    env: QUAYIO_DOCKER_PASSWORD
    
