name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  merge_group:
    types:
      - checks_requested
jobs:
  lint-code-base:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: yarn
      - name: Check TypeScript integrity
        run: yarn typecheck
      - name: Check .js and .ts code
        run: yarn lint-check
      - name: Run uvu tests
        run: yarn uvu-test
      - name: Attempt to build the docs
        run: yarn update-and-build
