name: Build Docs Image
run-name: Build Docs Image
on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  DOCKER_IMAGE: ghcr.io/gravitational/docs:latest

jobs:
  buildbox:
    name: Build Docs Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Docs
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build buildbox image
        run: make docker-image

      - name: Docker push the latest built image
        run: make docker-push
